### ISSUE TITLE
map is showing very clumsy in java 1.19.3

### ISSUE THREAD

**Issue by Damuammu** [Draradech/FlowerMap#1]
why map is showing very clumsy in java 1.19.3. i dont know how to share screenshot here. Please can help on this
![2023-04-08_20 14 19](https://user-images.githubusercontent.com/749993/230727532-3843d773-dc49-4b7a-9dd8-2068be5224c3.png)

**Comment by Draradech** [comment]
I'm not sure what you are asking? I'm going to guess:

- The noise effect is caused by the fact that in most biomes multiple different flowers can grow in one spot. In a flower forest that isn't the case and the map will be stable.
- The map scale can be changed in the config menu
- You have another minimap mod active at the same time, which looks a bit weird (the coordinates and half border are not from my mod)

If you meant something else I apologize, can you clarify?

**Comment by Damuammu** [comment]
ya sorry not clear on issue, i moved the mini map to left and i see lot of noise on flower map. that is what i want to check.

**Comment by Draradech** [comment]
Yes. The noise is expected. The mod asks the base game "which flower will grow here" and gets a different answer every time.

**Comment by Damuammu** [comment]
got it thanks. final question. does same flowermap used in this video? or its different

**Comment by Draradech** [comment]
which video?

**Comment by LangKeWAVE** [comment]
Yes, the game will taste the flowers that spawn different colors at each time slot

> Yes. The noise is expected. The mod asks the base game "which flower will grow here" and gets a different answer every time.
